In [1]:
import pandas as pd

In [7]:
#Series de pandas 
numeros = [1, 2, 3, 4, 5, 6, 7, 8 , 9]
series = pd.Series(numeros) 
series, type(series)

(0    1
 1    2
 2    3
 3    4
 4    5
 5    6
 6    7
 7    8
 8    9
 dtype: int64,
 pandas.core.series.Series)

In [8]:
data = { "nombres": ["Ana", "Luis", "Carlos", "María", "Juan"],
         "edades": [23, 45, 31, 35, 28],
         "municipios":["Tultitlán", "Ecatepec", "Naucalpan", "Nezahualcóyotl", "Chimalhuacán"],
         "ciudad":["san pablo de las salinas", "San Cristobal", "San Bartolo", "nezahualcóyotl", "chimalhuacán"]}
print(data), type(data)

{'nombres': ['Ana', 'Luis', 'Carlos', 'María', 'Juan'], 'edades': [23, 45, 31, 35, 28], 'municipios': ['Tultitlán', 'Ecatepec', 'Naucalpan', 'Nezahualcóyotl', 'Chimalhuacán'], 'ciudad': ['san pablo de las salinas', 'San Cristobal', 'San Bartolo', 'nezahualcóyotl', 'chimalhuacán']}

(None, dict)

In [55]:
#primer DataFrame apartir de un diccionario 
df=pd.DataFrame(data=data)
df

  nombres  edades      municipios                    ciudad
0     Ana      23       Tultitlán  san pablo de las salinas
1    Luis      45        Ecatepec             San Cristobal
2  Carlos      31       Naucalpan               San Bartolo
3   María      35  Nezahualcóyotl            nezahualcóyotl
4    Juan      28    Chimalhuacán              chimalhuacán

In [25]:
df.to_csv("data.csv", index=False)  # Guardar DataFrame en un archivo CSV sin el índice

In [22]:
 #importar un archivo csv
import_df = pd.read_csv("data.csv", index_col=0) 
import_df.head()

  nombres  edades      municipios                    ciudad
0     Ana      23       Tultitlán  san pablo de las salinas
1    Luis      45        Ecatepec             San Cristobal
2  Carlos      31       Naucalpan               San Bartolo
3   María      35  Nezahualcóyotl            nezahualcóyotl
4    Juan      28    Chimalhuacán              chimalhuacán

In [49]:
##nombres = df ["nombres"] 
#print(nombres)

chismes= (df["edades"]>=30 ) & (df["ciudad"].str.startswith("S"))
df[chismes]

  nombres  edades municipios         ciudad
1    Luis      45   Ecatepec  San Cristobal
2  Carlos      31  Naucalpan    San Bartolo

In [50]:
df.query('edades >= 30 and ciudad.str.startswith("S")', engine='python')

  nombres  edades municipios         ciudad
1    Luis      45   Ecatepec  San Cristobal
2  Carlos      31  Naucalpan    San Bartolo

In [54]:
df[df["nombres"].isin(["Ana","María","Carlos"  ])]

  nombres  edades      municipios                    ciudad
0     Ana      23       Tultitlán  san pablo de las salinas
2  Carlos      31       Naucalpan               San Bartolo
3   María      35  Nezahualcóyotl            nezahualcóyotl

In [2]:
import numpy as np 
import pandas as pd 
data = {
    "La Llorona": { 
        "año":1512,
        "origen": "Leyenda popular mexicana",
        "arma": "Lamentos que atraen a los incautos",
        "descripcion": "Espíritu de una mujer que llora por sus hijos, suele aparecer cerca de ríos o caminos solitarios."
    },
    "El Charro Negro": {
        "año": 1833,
        "origen": "Folclore mexicano",
        "arma": None,
        "descripcion": "Entidad que ofrece riquezas a cambio del alma; aparece como un elegante jinete vestido de negro."
    },
    "El Nahual": {
        "año": np.nan,
        "origen": "Mitología mesoamericana",
        "arma": "Transformación en animales",
        "descripcion": "Brujo o chamán que puede convertirse en animales para hacer daño o proteger."
    },
    "La Pascualita": { 
        "año": 1930,
        "origen": "Chihuahua, México",
        "arma": "Presencia inquietante",
        "descripcion": "Maniquí de una tienda de novias que se rumorea es el cuerpo embalsamado de una joven fallecida."
    },
    "El Cadejo": { 
        "año": np.nan,
        "origen": "Leyenda centroamericana con presencia en México",
        "arma": "Aparición sobrenatural",
        "descripcion": "Criatura parecida a un perro que puede proteger o atacar según su color (blanco o negro)."
    },
    "La Planchada": {
        "año": 1943,
        "origen": "Leyenda urbana de hospitales mexicanos",
        "arma": "Apariciones en hospitales",
        "descripcion": "Fantasma de una enfermera que aparece en hospitales para atender a los pacientes."
    }
} 
df = pd.DataFrame(data).T
df 
data_fill = df.fillna({
    "año": df["año"].mean(),
    "arma": "Desconocida",
  
}) 
data_fill

C:\Users\becsistemas\AppData\Local\Temp\ipykernel_28312\992199990.py:43: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_fill = df.fillna({

,año,origen,arma,descripcion
La Llorona,1512.0,Leyenda popular mexicana,Lamentos que atraen a los incautos,"Espíritu de una mujer que llora por sus hijos,..."
El Charro Negro,1833.0,Folclore mexicano,Desconocida,Entidad que ofrece riquezas a cambio del alma;...
El Nahual,1804.5,Mitología mesoamericana,Transformación en animales,Brujo o chamán que puede convertirse en animal...
La Pascualita,1930.0,"Chihuahua, México",Presencia inquietante,Maniquí de una tienda de novias que se rumorea...
El Cadejo,1804.5,Leyenda centroamericana con presencia en México,Aparición sobrenatural,Criatura parecida a un perro que puede protege...
La Planchada,1943.0,Leyenda urbana de hospitales mexicanos,Apariciones en hospitales,Fantasma de una enfermera que aparece en hospi...

,La Llorona,El Charro Negro,El Nahual,La Pascualita,El Cadejo,La Planchada
año,1512,1833,NaN,1930,NaN,1943
origen,Leyenda popular mexicana,Folclore mexicano,Mitología mesoamericana,"Chihuahua, México",Leyenda centroamericana con presencia en México,Leyenda urbana de hospitales mexicanos
arma,Lamentos que atraen a los incautos,None,Transformación en animales,Presencia inquietante,Aparición sobrenatural,Apariciones en hospitales
descripcion,"Espíritu de una mujer que llora por sus hijos,...",Entidad que ofrece riquezas a cambio del alma;...,Brujo o chamán que puede convertirse en animal...,Maniquí de una tienda de novias que se rumorea...,Criatura parecida a un perro que puede protege...,Fantasma de una enfermera que aparece en hospi...